language: node_js
node_js:
  - "stable"
  - "8"

install:
  - npm install

script:
  - npm run test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
